package com.a_blekot.shlokas.android_ui.theme

import androidx.compose.material3.MaterialTheme.colorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color


@Composable
fun dialogBgColor() =
    colorScheme.onBackground.copy(alpha = 0.5f)

val md_theme_light_primary = Color(0xFF7A564A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onPrimaryContainer = Color(0xFF2E140C)
val md_theme_light_secondary = Color(0xFF695C58)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF1DFD9)
val md_theme_light_onSecondaryContainer = Color(0xFF231917)
val md_theme_light_tertiary = Color(0xFF645E4D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBE2CC)
val md_theme_light_onTertiaryContainer = Color(0xFF1F1B0E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B1A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B1A)
val md_theme_light_surfaceVariant = Color(0xFFEBE0DD)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4544)
val md_theme_light_outline = Color(0xFF7D7573)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF33302F)
val md_theme_light_inverseOnSurface = Color(0xFFF7EFED)
val md_theme_light_inversePrimary = Color(0xFFEBBCAD)
val md_theme_light_surfaceTint = Color(0xFF7A564A)

val md_theme_dark_primary = Color(0xFFEBBCAD)
val md_theme_dark_onPrimary = Color(0xFF47291F)
val md_theme_dark_primaryContainer = Color(0xFF603F34)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_secondary = Color(0xFFD4C3BE)
val md_theme_dark_onSecondary = Color(0xFF392E2B)
val md_theme_dark_secondaryContainer = Color(0xFF504441)
val md_theme_dark_onSecondaryContainer = Color(0xFFF1DFD9)
val md_theme_dark_tertiary = Color(0xFFCEC6B1)
val md_theme_dark_onTertiary = Color(0xFF353022)
val md_theme_dark_tertiaryContainer = Color(0xFF4C4637)
val md_theme_dark_onTertiaryContainer = Color(0xFFEBE2CC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1E1B1A)
val md_theme_dark_onBackground = Color(0xFFE8E1DF)
val md_theme_dark_surface = Color(0xFF1E1B1A)
val md_theme_dark_onSurface = Color(0xFFE8E1DF)
val md_theme_dark_surfaceVariant = Color(0xFF4C4544)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC4C2)
val md_theme_dark_outline = Color(0xFF978F8D)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE8E1DF)
val md_theme_dark_inverseOnSurface = Color(0xFF33302F)
val md_theme_dark_inversePrimary = Color(0xFF7A564A)
val md_theme_dark_surfaceTint = Color(0xFFEBBCAD)


val seed = Color(0xFFFECDBE)

//PINK
//val md_theme_light_primary = Color(0xFFA92E62)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFFFD9E2)
//val md_theme_light_onPrimaryContainer = Color(0xFF3E001D)
//val md_theme_light_secondary = Color(0xFF4A58A9)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFDEE0FF)
//val md_theme_light_onSecondaryContainer = Color(0xFF000F5C)
//val md_theme_light_tertiary = Color(0xFF006685)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFBFE9FF)
//val md_theme_light_onTertiaryContainer = Color(0xFF001F2A)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFFFBFF)
//val md_theme_light_onBackground = Color(0xFF201A1B)
//val md_theme_light_surface = Color(0xFFFFFBFF)
//val md_theme_light_onSurface = Color(0xFF201A1B)
//val md_theme_light_surfaceVariant = Color(0xFFF2DDE1)
//val md_theme_light_onSurfaceVariant = Color(0xFF514347)
//val md_theme_light_outline = Color(0xFF837377)
//val md_theme_light_inverseOnSurface = Color(0xFFFAEEEF)
//val md_theme_light_inverseSurface = Color(0xFF352F30)
//val md_theme_light_inversePrimary = Color(0xFFFFB1C8)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFFA92E62)
//
//val md_theme_dark_primary = Color(0xFFFFB1C8)
//val md_theme_dark_onPrimary = Color(0xFF650033)
//val md_theme_dark_primaryContainer = Color(0xFF89114A)
//val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E2)
//val md_theme_dark_secondary = Color(0xFFBBC3FF)
//val md_theme_dark_onSecondary = Color(0xFF172778)
//val md_theme_dark_secondaryContainer = Color(0xFF313F90)
//val md_theme_dark_onSecondaryContainer = Color(0xFFDEE0FF)
//val md_theme_dark_tertiary = Color(0xFF6CD2FF)
//val md_theme_dark_onTertiary = Color(0xFF003547)
//val md_theme_dark_tertiaryContainer = Color(0xFF004D65)
//val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9FF)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF201A1B)
//val md_theme_dark_onBackground = Color(0xFFEBE0E1)
//val md_theme_dark_surface = Color(0xFF201A1B)
//val md_theme_dark_onSurface = Color(0xFFEBE0E1)
//val md_theme_dark_surfaceVariant = Color(0xFF514347)
//val md_theme_dark_onSurfaceVariant = Color(0xFFD5C2C6)
//val md_theme_dark_outline = Color(0xFF9E8C90)
//val md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
//val md_theme_dark_inverseSurface = Color(0xFFEBE0E1)
//val md_theme_dark_inversePrimary = Color(0xFFA92E62)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFFFFB1C8)
//
//
//val seed = Color(0xFFAA2F63)

//blue
//val md_theme_light_primary = Color(0xFF0056D1)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFDAE2FF)
//val md_theme_light_onPrimaryContainer = Color(0xFF001847)
//val md_theme_light_secondary = Color(0xFF005FAE)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFD4E3FF)
//val md_theme_light_onSecondaryContainer = Color(0xFF001C3A)
//val md_theme_light_tertiary = Color(0xFF735471)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFFED7F9)
//val md_theme_light_onTertiaryContainer = Color(0xFF2B122C)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFEFBFF)
//val md_theme_light_onBackground = Color(0xFF1B1B1F)
//val md_theme_light_surface = Color(0xFFFEFBFF)
//val md_theme_light_onSurface = Color(0xFF1B1B1F)
//val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
//val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
//val md_theme_light_outline = Color(0xFF757780)
//val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
//val md_theme_light_inverseSurface = Color(0xFF303034)
//val md_theme_light_inversePrimary = Color(0xFFB2C5FF)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFF0056D1)
//
//val md_theme_dark_primary = Color(0xFFB2C5FF)
//val md_theme_dark_onPrimary = Color(0xFF002C72)
//val md_theme_dark_primaryContainer = Color(0xFF0040A0)
//val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
//val md_theme_dark_secondary = Color(0xFFA5C8FF)
//val md_theme_dark_onSecondary = Color(0xFF00315E)
//val md_theme_dark_secondaryContainer = Color(0xFF004785)
//val md_theme_dark_onSecondaryContainer = Color(0xFFD4E3FF)
//val md_theme_dark_tertiary = Color(0xFFE1BBDD)
//val md_theme_dark_onTertiary = Color(0xFF412742)
//val md_theme_dark_tertiaryContainer = Color(0xFF5A3D59)
//val md_theme_dark_onTertiaryContainer = Color(0xFFFED7F9)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF1B1B1F)
//val md_theme_dark_onBackground = Color(0xFFE4E2E6)
//val md_theme_dark_surface = Color(0xFF1B1B1F)
//val md_theme_dark_onSurface = Color(0xFFE4E2E6)
//val md_theme_dark_surfaceVariant = Color(0xFF44464F)
//val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
//val md_theme_dark_outline = Color(0xFF8F9099)
//val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
//val md_theme_dark_inverseSurface = Color(0xFFE4E2E6)
//val md_theme_dark_inversePrimary = Color(0xFF0056D1)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFFB2C5FF)
//
//
//val seed = Color(0xFF0061E9)

//
//val md_theme_light_primary = Color(0xFF006877)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFA5EEFF)
//val md_theme_light_onPrimaryContainer = Color(0xFF001F25)
//val md_theme_light_secondary = Color(0xFF00696F)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFF75F5FF)
//val md_theme_light_onSecondaryContainer = Color(0xFF002022)
//val md_theme_light_tertiary = Color(0xFF555D7E)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFDCE1FF)
//val md_theme_light_onTertiaryContainer = Color(0xFF111A37)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFBFCFD)
//val md_theme_light_onBackground = Color(0xFF191C1D)
//val md_theme_light_surface = Color(0xFFFBFCFD)
//val md_theme_light_onSurface = Color(0xFF191C1D)
//val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
//val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
//val md_theme_light_outline = Color(0xFF6F797B)
//val md_theme_light_inverseOnSurface = Color(0xFFEFF1F2)
//val md_theme_light_inverseSurface = Color(0xFF2E3132)
//val md_theme_light_inversePrimary = Color(0xFF52D7F0)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFF006877)
//
//val md_theme_dark_primary = Color(0xFF52D7F0)
//val md_theme_dark_onPrimary = Color(0xFF00363F)
//val md_theme_dark_primaryContainer = Color(0xFF004E5A)
//val md_theme_dark_onPrimaryContainer = Color(0xFFA5EEFF)
//val md_theme_dark_secondary = Color(0xFF4CD9E3)
//val md_theme_dark_onSecondary = Color(0xFF00363A)
//val md_theme_dark_secondaryContainer = Color(0xFF004F54)
//val md_theme_dark_onSecondaryContainer = Color(0xFF75F5FF)
//val md_theme_dark_tertiary = Color(0xFFBDC5EB)
//val md_theme_dark_onTertiary = Color(0xFF272F4D)
//val md_theme_dark_tertiaryContainer = Color(0xFF3D4565)
//val md_theme_dark_onTertiaryContainer = Color(0xFFDCE1FF)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF191C1D)
//val md_theme_dark_onBackground = Color(0xFFE1E3E4)
//val md_theme_dark_surface = Color(0xFF191C1D)
//val md_theme_dark_onSurface = Color(0xFFE1E3E4)
//val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
//val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
//val md_theme_dark_outline = Color(0xFF899295)
//val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
//val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
//val md_theme_dark_inversePrimary = Color(0xFF006877)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFF52D7F0)
//
//
//val seed = Color(0xFF007586)
